apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deep-geology.fullname" . }}-worker
  labels:
    {{- include "deep-geology.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "deep-geology.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.api.runtimeSecret }}
          env:
            - name: AUTO_CREATE_SCHEMA
              value: "false"
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
