import type { ExternalResource } from '@/types'

export const fallbackResources: ExternalResource[] = [
  {
    id: 'petroleum-geology-ai',
    title: '石油地质学 AI 课程',
    provider: '雨课堂 AI 工作台',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 4,
    language: '中文',
    status: 'active',
    url: 'https://cup.yuketang.cn/ai-workspace/pro-ai-result-display/541',
    description: '校内 AI 课程建设成果展示。',
    sort_order: 36
  },
  {
    id: 'petroleum-geology-ai-foundation',
    title: '油矿地质学 AI 课程',
    provider: '雨课堂 AI 工作台',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 4,
    language: '中文',
    status: 'active',
    url: 'https://cup.yuketang.cn/ai-workspace/pro-ai-result-display/402',
    description: '校内 AI 课程建设成果展示。',
    sort_order: 36
  },
  {
    id: 'reservoir-characterization',
    title: '储层表征与建模',
    provider: '雨课堂研究生资源',
    category: 'courses',
    course_level: '研究生',
    audience: '地质资源与地质工程研究生',
    credits: 2,
    language: '中文',
    status: 'active',
    url: 'https://cup.yuketang.cn/pro/portal/resourcedetail/52953',
    description: '储层描述、表征方法与建模资源。',
    sort_order: 37
  },
  {
    id: 'oil-gas-exploration-graduate',
    title: 'Oil and Gas Field Exploration 研究生资源',
    provider: '雨课堂研究生资源',
    category: 'courses',
    course_level: '研究生',
    audience: '地质资源与地质工程研究生',
    language: 'English',
    status: 'active',
    url: 'https://cup.yuketang.cn/pro/portal/resourcedetail/12934655',
    description: '油气田勘探研究生课程资源。',
    sort_order: 38
  },
  // 以下 13 门与「专业大图谱」（MajorAtlas）同步；暂无平台入口的置 pending 显示「链接待补充」，拿到链接改 active + url 即可。
  {
    id: 'general-geology',
    title: '普通地质学',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 3,
    language: '中文',
    status: 'pending',
    url: null,
    description: '地质学基础概念与入门训练。',
    sort_order: 39
  },
  {
    id: 'earth-science-intro',
    title: '地球科学概论',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 2.5,
    language: '中文',
    status: 'pending',
    url: null,
    description: '地球科学整体框架概述。',
    sort_order: 40
  },
  {
    id: 'rock-forming-minerals',
    title: '造岩矿物学',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 3.5,
    language: '中文',
    status: 'pending',
    url: null,
    description: '造岩矿物鉴定与成因基础。',
    sort_order: 41
  },
  {
    id: 'sedimentary-petrology',
    title: '沉积岩石学',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 3,
    language: '中文',
    status: 'pending',
    url: null,
    description: '沉积作用与沉积岩基础。',
    sort_order: 42
  },
  {
    id: 'geophysical-logging',
    title: '地球物理测井',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 3,
    language: '中文',
    status: 'pending',
    url: null,
    description: '测井原理、方法与解释应用。',
    sort_order: 43
  },
  {
    id: 'elastic-wave-dynamics',
    title: '弹性波动力学',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 3,
    language: '中文',
    status: 'pending',
    url: null,
    description: '弹性波传播理论与动力学基础。',
    sort_order: 44
  },
  {
    id: 'seismic-wave-dynamics',
    title: '地震波动力学',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 3,
    language: '中文',
    status: 'pending',
    url: null,
    description: '地震波传播动力学理论。',
    sort_order: 45
  },
  {
    id: 'seismic-exploration-principles',
    title: '地震勘探原理',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 3,
    language: '中文',
    status: 'pending',
    url: null,
    description: '地震勘探基本原理与流程。',
    sort_order: 46
  },
  {
    id: 'reservoir-geology',
    title: '储层地质学',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 2.5,
    language: '中文',
    status: 'pending',
    url: null,
    description: '储层形成、特征与评价。',
    sort_order: 47
  },
  {
    id: 'seismic-data-processing',
    title: '地震资料数字处理',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 3,
    language: '中文',
    status: 'pending',
    url: null,
    description: '地震数据处理方法与流程。',
    sort_order: 48
  },
  {
    id: 'seismic-exploration-practice',
    title: '油气地震勘探实践',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 2,
    language: '中文',
    status: 'pending',
    url: null,
    description: '油气地震勘探实践训练。',
    sort_order: 49
  },
  {
    id: 'comprehensive-geology-internship',
    title: '地质综合实习',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 1.5,
    language: '中文',
    status: 'pending',
    url: null,
    description: '地质综合实践与野外训练。',
    sort_order: 50
  },
  {
    id: 'oil-gas-field-exploration',
    title: '油气田勘探',
    provider: '校内课程',
    category: 'courses',
    course_level: '本科',
    audience: '地质与石油工程专业学生',
    credits: 2.5,
    language: '中文',
    status: 'pending',
    url: null,
    description: '油气勘探方法流程与部署。',
    sort_order: 51
  },
  {
    id: 'clastic-rock-vr',
    title: '碎屑岩镜下观察虚拟仿真',
    provider: '中国石油大学（北京）虚拟仿真实验平台',
    category: 'practice',
    course_level: '本科',
    audience: '沉积岩石学与实验课程学生',
    language: '中文',
    status: 'active',
    url: 'https://vrlab.cup.edu.cn/virexp/prepare_login?alert=true&next=http%3A%2F%2Fvrlab.cup.edu.cn%2Fvirexp%2Fproject%2Fresult%2F%21studentElectiveView%3Fid%3D4a4c410b806a73e60184757a34976c02',
    description: '显微观察训练与碎屑岩识别实验。',
    sort_order: 50
  },
  {
    id: 'sedimentary-rock-vr',
    title: '沉积岩多尺度鉴定虚拟仿真',
    provider: '中国石油大学（北京）虚拟仿真实验平台',
    category: 'practice',
    course_level: '本科',
    audience: '沉积岩石学与实验课程学生',
    language: '中文',
    status: 'active',
    url: 'https://vrlab.cup.edu.cn/virexp/prepare_login?alert=true&next=http%3A%2F%2Fvrlab.cup.edu.cn%2Fvirexp%2Fproject%2Fresult%2F%21studentElectiveView%3Fid%3D4a4c410b87920b1c018b8f30c2132d9b',
    description: '基于宏观与微观证据的沉积岩多尺度鉴定。',
    sort_order: 52
  },
  {
    id: 'seismic-exploration-vr',
    title: '油气地震勘探虚拟仿真实验',
    provider: '中国石油大学（北京）虚拟仿真实验平台',
    category: 'practice',
    course_level: '本科',
    audience: '地球物理与勘探方向学生',
    language: '中文',
    status: 'active',
    url: 'https://vrlab.cup.edu.cn/virexp/prepare_login?alert=true&next=http%3A%2F%2Fvrlab.cup.edu.cn%2Fvirexp%2Fproject%2Fresult%2F%21studentElectiveView%3Fid%3D4a4c410b78edec07017918c978f17752',
    description: '油气地震勘探流程与数据解释训练。',
    sort_order: 54
  },
  {
    id: 'radioactive-logging-vr',
    title: '放射性测井虚拟仿真实验',
    provider: '中国石油大学（北京）虚拟仿真实验平台',
    category: 'practice',
    course_level: '本科',
    audience: '地球物理测井方向学生',
    language: '中文',
    status: 'active',
    url: 'https://vrlab.cup.edu.cn/virexp/prepare_login?alert=true&next=http%3A%2F%2Fvrlab.cup.edu.cn%2Fvirexp%2Fproject%2Fresult%2F%21studentElectiveView%3Fid%3D4a4c410b8ef44ebd018f802dbfe03df6',
    description: '放射性测井原理与解释过程虚拟实验。',
    sort_order: 56
  }
]
