"""内置模型供应商定义。"""

from typing import Any

BUILTIN_PROVIDERS: list[dict[str, Any]] = [
    {
        "provider_id": "local-ollama",
        "display_name": "校内 Ollama",
        "provider_type": "openai",
        "base_url": "http://10.120.57.231:11434/v1",
        "api_key_env": "LOCAL_OLLAMA_API_KEY",
        "capabilities": ["chat"],
        "models_endpoint": "/models",
        "enabled_models": [
            {
                "id": "qwen3.8:latest",
                "type": "chat",
                "display_name": "Qwen3.8（校内）",
                "context_length": 262144,
                "supported_parameters": ["tools"],
            }
        ],
    },
    {
        "provider_id": "openai",
        "display_name": "OpenAI",
        "base_url": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "models_endpoint": "https://api.openai.com/v1/models",
    },
    # {
    #     "provider_id": "anthropic",
    #     "display_name": "Anthropic",
    #     "base_url": "https://api.anthropic.com",
    #     "api_key_env": "ANTHROPIC_API_KEY",
    #     "models_endpoint": "https://api.anthropic.com/models",
    # },
    # {
    #     "provider_id": "google",
    #     "display_name": "Google Gemini",
    #     "base_url": "https://generativelanguage.googleapis.com",
    #     "api_key_env": "GEMINI_API_KEY",
    #     "models_endpoint": "https://generativelanguage.googleapis.com/v1beta/models",
    # },
    {
        "provider_id": "deepseek",
        "display_name": "DeepSeek",
        "base_url": "https://api.deepseek.com",
        "api_key_env": "DEEPSEEK_API_KEY",
        "models_endpoint": "https://api.deepseek.com/models",
    },
    {
        "provider_id": "alibaba-cn",
        "display_name": "DashScope",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "embedding_base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1/embeddings",
        "rerank_base_url": "https://dashscope.aliyuncs.com/compatible-api/v1/reranks",
        "api_key_env": "DASHSCOPE_API_KEY",
        "capabilities": ["chat", "embedding", "rerank"],
        "models_endpoint": "https://dashscope.aliyuncs.com/compatible-mode/v1/models",
        "enabled_models": [
            {
                "id": "qwen-turbo",
                "type": "chat",
                "display_name": "Qwen-Turbo（阿里云）",
                "context_length": 131072,
            },
            {
                "id": "text-embedding-v4",
                "type": "embedding",
                "display_name": "text-embedding-v4",
                "dimension": 1024,
            },
            {
                "id": "qwen3-rerank",
                "type": "rerank",
                "display_name": "qwen3-rerank",
            },
        ],
    },
    {
        "provider_id": "alibaba",
        "display_name": "DashScope (International)",
        "base_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        "api_key_env": "DASHSCOPE_API_KEY",
        "models_endpoint": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/models",
    },
    {
        "provider_id": "alibaba-coding-plan-cn",
        "display_name": "Aliyun Coding Plan",
        "base_url": "https://coding.dashscope.aliyuncs.com/v1",
        "api_key_env": "DASHSCOPE_API_KEY",
        "models_endpoint": "https://coding.dashscope.aliyuncs.com/v1/models",
    },
    {
        "provider_id": "alibaba-coding-plan",
        "display_name": "Aliyun Coding Plan (International)",
        "base_url": "https://coding-intl.dashscope.aliyuncs.com/v1",
        "api_key_env": "DASHSCOPE_API_KEY",
        "models_endpoint": "https://coding-intl.dashscope.aliyuncs.com/v1/models",
    },
    {
        "provider_id": "zhipuai",
        "display_name": "Zhipu (BigModel)",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "api_key_env": "ZHIPUAI_API_KEY",
        "models_endpoint": "https://open.bigmodel.cn/api/paas/v4/models",
    },
    {
        "provider_id": "zhipuai-coding-plan",
        "display_name": "Zhipu Coding Plan (BigModel)",
        "base_url": "https://open.bigmodel.cn/api/coding/paas/v4",
        "api_key_env": "ZHIPUAI_API_KEY",
        "models_endpoint": "https://open.bigmodel.cn/api/coding/paas/v4/models",
    },
    {
        "provider_id": "zai",
        "display_name": "Zhipu (Z.AI)",
        "base_url": "https://api.z.ai/api/paas/v4",
        "api_key_env": "ZAI_API_KEY",
        "models_endpoint": "https://api.z.ai/api/paas/v4/models",
    },
    {
        "provider_id": "zai-coding-plan",
        "display_name": "Zhipu Coding Plan (Z.AI)",
        "base_url": "https://api.z.ai/api/coding/paas/v4",
        "api_key_env": "ZAI_API_KEY",
        "models_endpoint": "https://api.z.ai/api/coding/paas/v4/models",
    },
    {
        "provider_id": "xiaomi-token-plan-cn",
        "display_name": "XiaomiMiMo Token Plan",
        "base_url": "https://token-plan-cn.xiaomimimo.com/v1",
        "api_key_env": "XIAOMI_MIMO_TOKEN_PLAN_API_KEY",
        "models_endpoint": "https://token-plan-cn.xiaomimimo.com/v1/models",
    },
    {
        "provider_id": "xiaomi",
        "display_name": "XiaomiMiMo",
        "base_url": "https://api.xiaomimimo.com/v1",
        "api_key_env": "XIAOMI_MIMO_API_KEY",
        "models_endpoint": "https://api.xiaomimimo.com/v1/models",
    },
    {
        "provider_id": "kimi-for-coding",
        "display_name": "Kimi Code",
        "base_url": "https://api.kimi.com/coding/v1",
        "api_key_env": "KIMI_CODE_API_KEY",
        "models_endpoint": "https://api.kimi.com/coding/v1/models",
    },
    {
        "provider_id": "moonshotai-cn",
        "display_name": "Moonshot",
        "base_url": "https://api.moonshot.cn/v1",
        "api_key_env": "MOONSHOT_API_KEY",
        "models_endpoint": "https://api.moonshot.cn/v1/models",
    },
    {
        "provider_id": "moonshotai",
        "display_name": "Moonshot (International)",
        "base_url": "https://api.moonshot.ai/v1",
        "api_key_env": "MOONSHOT_API_KEY",
        "models_endpoint": "https://api.moonshot.ai/v1/models",
    },
    {
        "provider_id": "minimax-cn",
        "display_name": "MiniMax",
        "base_url": "https://api.minimaxi.com/v1",
        "api_key_env": "MINIMAX_API_KEY",
        "models_endpoint": "https://api.minimaxi.com/v1/models",
    },
    {
        "provider_id": "minimax",
        "display_name": "MiniMax (International)",
        "base_url": "https://api.minimax.io/v1",
        "api_key_env": "MINIMAX_API_KEY",
        "models_endpoint": "https://api.minimax.io/v1/models",
    },
    {
        "provider_id": "openrouter",
        "display_name": "OpenRouter",
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
        "capabilities": ["chat", "embedding"],
        "embedding_base_url": "https://openrouter.ai/api/v1/embeddings",
        "models_endpoint": "https://openrouter.ai/api/v1/models",
        "embedding_models_endpoint": "https://openrouter.ai/api/v1/embeddings/models",
    },
    {
        "provider_id": "modelscope",
        "display_name": "ModelScope",
        "base_url": "https://api-inference.modelscope.cn/v1",
        "api_key_env": "MODELSCOPE_ACCESS_TOKEN",
        "models_endpoint": "https://api-inference.modelscope.cn/v1/models",
    },
    {
        "provider_id": "opencode",
        "display_name": "OpenCode",
        "base_url": "https://opencode.ai/zen/v1",
        "models_endpoint": "https://opencode.ai/zen/v1/models",
    },
    {
        "provider_id": "opencode-go",
        "display_name": "OpenCode Go",
        "base_url": "https://opencode.ai/zen/go/v1",
        "models_endpoint": "https://opencode.ai/zen/go/v1/models",
    },
]
